version: '3.7'

services:
  postgres:
    image: postgres:15
    container_name: e-learning-server
    restart: always
    environment:
      - POSTGRES_USER=e-learning
      - POSTGRES_PASSWORD=e-learning
      - POSTGRES_DB=e-learning-db
    ports:
      - '5438:5432'
